### ISSUE TITLE
Support for react-native 0.60+?

### ISSUE THREAD

**Issue by ronit-kadwane** [manse/react-native-brightcove-player#30]
Hello,
As react-native has implemented many new features, native supports and security updates in version 0.60+, So I want to upgrade my project.
But unfortunately, this plugin is not supporting to react-native 0.60+ (**iOS**).(`error: double-conversion/double-conversion.h' file not found` due to `use_frameworks!` in Podfiles.)

Can you please brief any road map or timeline for next release of react-native-brightcove-player which supports react-native 0.60+?
If you brief, It would be very helpful to make a decision.
Thank you.

**Comment by manse** [comment]
I realized that the specification of RN library will change from 0.60. But I don't know how to support 0.60, so I want to see how other major libraries handle the newest RN. ( I couldn't find 0.60 supported library )
It will take several weeks to several months, I think.

**Comment by ronit-kadwane** [comment]
@manse Thanks for the reply.
Hoping it would be updated soon.

**Comment by nlabofa** [comment]
@manse does it support version 0.60+ now ?

**Comment by simongough** [comment]
@manse Just wondering if there's any update on the 0.60+ as yet?  Is this something that's likely to be added soon?

**Comment by samridhgupta** [comment]
Any update ?
I have a new RN project using 0.60.5 and I am unable to link this package with my project.
Please Help

**Comment by manse** [comment]
Hi there,
I just published to npm a version that supported react-native 0.60 with working example. 
Please check it.

**Comment by i3i2uno** [comment]
@manse I keep getting this error on Android once the app is launched and the `<BrightcovePlayer />` is rendered for the first time. It is a Fatal Exception.

I have tried on both RN 0.61.4 and RN 0.60.6

`java.lang.NoSuchMethodError: No virtual method setEventListener(Landroid/os/Handler;Lcom/google/android/exoplayer2/upstream/BandwidthMeter$EventListener;)Lcom/google/android/exoplayer2/upstream/DefaultBandwidthMeter$Builder; in class Lcom/google/android/exoplayer2/upstream/DefaultBandwidthMeter$Builder; or its super classes (declaration of 'com.google.android.exoplayer2.upstream.DefaultBandwidthMeter$Builder' appears in /data/app/com.progresif-2XsCX-fgiZJgREPviMXg1w==/base.apk)
        at com.brightcove.player.network.PlayerBandwidthMeter.<init>(PlayerBandwidthMeter.java:70)
        at com.brightcove.player.display.ExoPlayerVideoDisplayComponent.<init>(ExoPlayerVideoDisplayComponent.java:817)
        at com.brightcove.player.view.BrightcoveExoPlayerVideoView.createVideoDisplayComponent(BrightcoveExoPlayerVideoView.java:71)
        at com.brightcove.player.view.BaseVideoView.setEventEmitter(BaseVideoView.java:395)
        at com.brightcove.player.view.BaseVideoView.finishInitialization(BaseVideoView.java:328)
        at jp.manse.BrightcovePlayerView.<init>(BrightcovePlayerView.java:70)
        at jp.manse.BrightcovePlayerManager.createViewInstance(BrightcovePlayerManager.java:43)
        at jp.manse.BrightcovePlayerManager.createViewInstance(BrightcovePlayerManager.java:17)
        at com.facebook.react.uimanager.ViewManager.createViewInstanceWithProps(ViewManager.java:119)
        at com.facebook.react.uimanager.ViewManager.createViewWithProps(ViewManager.java:66)
        at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:259)
        at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:198)
        at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:838)
        at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:952)
        at com.facebook.react.uimanager.UIViewOperationQueue.access$2200(UIViewOperationQueue.java:44)
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1012)
        at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
        at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:172)
        at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:84)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:947)
        at android.view.Choreographer.doCallbacks(Choreographer.java:761)
        at android.view.Choreographer.doFrame(Choreographer.java:693)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)`

Any guidance would be much appreciated! Thanks!

**Comment by manse** [comment]
@i3i2uno On Android simulator, it does not work correctly in some cases. Please use actual device.

**Comment by i3i2uno** [comment]
@manse Yea I tried that after seeing it in the readme. Same result.

It errors at this method in the PlayerBandwidthMeter.class:

`public PlayerBandwidthMeter(@Nullable Context context, @Nullable Handler eventHandler, @Nullable EventListener eventListener) {
        this((new Builder(context)).setEventListener(eventHandler, eventListener).build());
    }`

**Comment by i3i2uno** [comment]
False alarm. The issue with my project was the fact that I had react-native-track-player as a dependency as well, and because of that, there are conflicting ExoPlayers within the project. Brightcove just caught the blame because thats where it was erroring first. Sorry about that @manse

**Comment by manse** [comment]
@i3i2uno I got it. Thanks for sharing knowledge.

**Comment by SystemBlad** [comment]
> False alarm. The issue with my project was the fact that I had react-native-track-player as a dependency as well, and because of that, there are conflicting ExoPlayers within the project. Brightcove just caught the blame because thats where it was erroring first. Sorry about that @manse

Hi. @i3i2uno Could you explain how had you resolved the ExoPlayers conflict? I am using the same laybraries.

**Comment by i3i2uno** [comment]
Been a while, and I don't work on this project anymore, but I took a quick glance at the code and I believe this is what solved that problem  @SystemBlad

```
// android\build.gradle

allprojects {
    configurations.all {
        resolutionStrategy {
            eachDependency { DependencyResolveDetails details ->
                if (details.requested.name.contains('exoplayer2')) {
                    println(details.requested)
                    details.useVersion "6.8.1"
                }
            }
        }
    }
}
```

**Comment by mustafakameldev** [comment]
@SystemBlad @i3i2uno  I use same libraries and i tried https://github.com/quipper/react-native-brightcove-player/issues/30#issuecomment-1034328726 but it doesn't work too, any updates ?
